train:
  _target_: src.datasets.ASVSpoofDataset
  name: "train"
  instance_transforms: ${transforms.instance_transforms.train}

val:
  _target_: src.datasets.ASVSpoofDataset
  name: "dev"
  instance_transforms: ${transforms.instance_transforms.inference}